from fastapi import APIRouter, Depends, HTTPException
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from typing import Optional

from app.features.curriculum.schemas import (
    CurriculumRequest,
    CurriculumResponse,
    SavedCurriculumSummary,
    SavedCurriculumDetail,
    ProgressUpdateRequest,
)
from app.features.curriculum.services import CurriculumService
from app.features.curriculum import persistence
from app.middleware.auth_middleware import get_current_user

router = APIRouter(prefix="/api/curriculum", tags=["curriculum"])

_optional_bearer = HTTPBearer(auto_error=False)


# ---------- Routes ----------

@router.post("/generate", response_model=CurriculumResponse)
async def generate_curriculum(
    body: CurriculumRequest,
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(_optional_bearer),
):
    """
    Generate a structured course curriculum based on the user's skill gaps.

    If a valid JWT is provided in the Authorization header, the result is
    automatically saved to Appwrite so it appears on the user's dashboard.
    """
    try:
        service = CurriculumService()
        result = await service.generate_curriculum(body)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Curriculum generation failed: {e}")

    # --- Auto-save when user is authenticated ---
    if credentials:
        try:
            from app.databases.appwrite_client import get_appwrite_client
            from app.features.auth.services import AuthService
            client = get_appwrite_client()
            user = AuthService(client).get_user(credentials.credentials)
            persistence.save_curriculum(user["id"], body.course_topic, result)
        except Exception as save_err:
            # Log but don't fail — saving is best-effort
            import logging
            logging.getLogger(__name__).warning("Failed to save curriculum: %s", save_err)

    return result


@router.get("/saved", response_model=list[SavedCurriculumSummary])
async def list_saved_curricula(user: dict = Depends(get_current_user)):
    """Return all curricula previously generated by the authenticated user."""
    try:
        return persistence.list_curricula(user["id"])
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch curricula: {e}")


@router.get("/saved/{curriculum_id}", response_model=SavedCurriculumDetail)
async def get_saved_curriculum(
    curriculum_id: str,
    user: dict = Depends(get_current_user),
):
    """Return a specific saved curriculum with full module data."""
    result = persistence.get_curriculum_detail(user["id"], curriculum_id)
    if result is None:
        raise HTTPException(status_code=404, detail="Curriculum not found")
    return result


@router.delete("/saved/{curriculum_id}", status_code=204)
async def delete_saved_curriculum(
    curriculum_id: str,
    user: dict = Depends(get_current_user),
):
    """Delete a specific saved curriculum."""
    deleted = persistence.delete_curriculum(user["id"], curriculum_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Curriculum not found")


@router.put("/saved/{curriculum_id}/progress", status_code=200)
async def update_curriculum_progress(
    curriculum_id: str,
    body: ProgressUpdateRequest,
    user: dict = Depends(get_current_user),
):
    """
    Persist the list of completed lesson IDs for a curriculum.
    This replaces the full list each time (idempotent).
    """
    updated = persistence.update_progress(user["id"], curriculum_id, body.completed_lessons)
    if not updated:
        raise HTTPException(status_code=404, detail="Curriculum not found")
    return {"ok": True}
