from fastapi import APIRouter, Depends, HTTPException
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from typing import Optional

from app.features.curriculum.schemas import (
    CurriculumRequest,
    CurriculumResponse,
    SavedCurriculumSummary,
    SavedCurriculumDetail,
    ProgressUpdateRequest,
    ModuleItem,
    TranscriptResponse,
)
from app.features.curriculum.services import CurriculumService
from app.features.curriculum import persistence
from app.features.fl_engine.schemas import TestSubmission
from app.features.fl_engine.orchestrator import get_orchestrator
from app.middleware.auth_middleware import get_current_user

router = APIRouter(prefix="/api/curriculum", tags=["curriculum"])

_optional_bearer = HTTPBearer(auto_error=False)


# ---------- Routes ----------

@router.post("/generate", response_model=CurriculumResponse)
async def generate_curriculum(
    body: CurriculumRequest,
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(_optional_bearer),
):
    """
    Generate a structured course curriculum based on the user's skill gaps.

    If a valid JWT is provided in the Authorization header, the result is
    automatically saved to Appwrite so it appears on the user's dashboard.
    """
    try:
        service = CurriculumService()
        result = await service.generate_curriculum(body)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Curriculum generation failed: {e}")

    # --- Auto-save when user is authenticated ---
    if credentials:
        try:
            from app.databases.appwrite_client import get_appwrite_client
            from app.features.auth.services import AuthService
            client = get_appwrite_client()
            user = AuthService(client).get_user(credentials.credentials)
            persistence.save_curriculum(user["id"], body.course_topic, result)
        except Exception as save_err:
            # Log but don't fail — saving is best-effort
            import logging
            logging.getLogger(__name__).warning("Failed to save curriculum: %s", save_err)

    return result


@router.post("/adapt")
async def adapt_curriculum(body: TestSubmission):
    """
    Submit test answers → FL assesses comprehension → LLM adapts the module.

    This is the core FL integration endpoint. The flow:
    1. Student submits test answers for a module
    2. FL engine assesses comprehension (weak/partial/strong)
    3. CurriculumService asks the LLM to expand, shorten, or maintain the module
    4. Returns the adaptation recommendation

    Works like a real teacher: if the student is struggling, break the
    module into smaller pieces. If they're excelling, advance faster.
    """
    try:
        # Step 1: Run FL assessment on the test answers
        orchestrator = get_orchestrator()
        answers = [
            {
                "question": a.question,
                "student_answer": a.student_answer,
                "correct_answer": a.correct_answer,
            }
            for a in body.answers
        ]
        assessment = orchestrator.assess_student(answers)

        # Step 2: Create a placeholder module for adaptation
        # In a full integration, this would look up the actual module
        module = ModuleItem(
            module_number=1,
            module_title=body.module_id or "Current Module",
            learning_objective="Master the concepts covered in this assessment",
            total_duration_minutes=60,
            videos=[],
        )

        # Step 3: Let the LLM adapt the curriculum based on FL assessment
        service = CurriculumService()
        course_topic = body.curriculum_id or "General"
        adaptation = await service.adapt_curriculum(module, assessment, course_topic)

        return {
            "assessment": assessment,
            "adaptation": adaptation,
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Curriculum adaptation failed: {str(e)}",
        )


@router.get("/saved", response_model=list[SavedCurriculumSummary])
async def list_saved_curricula(user: dict = Depends(get_current_user)):
    """Return all curricula previously generated by the authenticated user."""
    try:
        return persistence.list_curricula(user["id"])
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch curricula: {e}")


@router.get("/saved/{curriculum_id}", response_model=SavedCurriculumDetail)
async def get_saved_curriculum(
    curriculum_id: str,
    user: dict = Depends(get_current_user),
):
    """Return a specific saved curriculum with full module data."""
    result = persistence.get_curriculum_detail(user["id"], curriculum_id)
    if result is None:
        raise HTTPException(status_code=404, detail="Curriculum not found")
    return result


@router.delete("/saved/{curriculum_id}", status_code=204)
async def delete_saved_curriculum(
    curriculum_id: str,
    user: dict = Depends(get_current_user),
):
    """Delete a specific saved curriculum."""
    deleted = persistence.delete_curriculum(user["id"], curriculum_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Curriculum not found")


@router.put("/saved/{curriculum_id}/progress", status_code=200)
async def update_curriculum_progress(
    curriculum_id: str,
    body: ProgressUpdateRequest,
    user: dict = Depends(get_current_user),
):
    """
    Persist the list of completed lesson IDs for a curriculum.
    This replaces the full list each time (idempotent).
    """
    updated = persistence.update_progress(user["id"], curriculum_id, body.completed_lessons)
    if not updated:
        raise HTTPException(status_code=404, detail="Curriculum not found")
    return {"ok": True}


@router.get("/transcript", response_model=TranscriptResponse)
async def get_video_transcript(youtube_url: str):
    """Fetch the English transcript of a YouTube video."""
    import re
    from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled, NoTranscriptFound

    video_id = None
    # Support regular and short YouTube URLs
    match = re.search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", youtube_url)
    if match:
        video_id = match.group(1)
    
    if not video_id:
        raise HTTPException(status_code=400, detail="Invalid YouTube URL - couldn't extract video ID")

    try:
        transcript_list = YouTubeTranscriptApi.get_transcript(video_id, languages=['en'])
        full_text = " ".join([t['text'] for t in transcript_list]).replace('\n', ' ')
        return TranscriptResponse(url=youtube_url, transcript=full_text)
    except Exception as e:
        raise HTTPException(status_code=404, detail=f"Transcript unavailable: {str(e)}")
